[build]
  publish = ".next"
  command = "npm run build"
  
[[plugins]]
  package = "@netlify/plugin-nextjs" 
  
[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_USE_NETLIFY_FORMS = "true"
